###
GET http://localhost:3000/api/loans
Content-Type: application/json


### APPLY FOR A LOAN
# rate => percentage
# time => time
POST http://localhost:3000/api/loans/
Content-Type: application/json

{
    "customerId": "f40b2365-8e0c-4c57-abd8-a1a0f9cdbcc9",
    "userId": "clnyb2sz70000pzmbclllxalf",
    "principal": 3000.00,
    "rate": 30,
    "time": 3
}