### Register new Company Agents

POST http://localhost:3000/api/customers/register
Content-Type: application/json

{
    "firstName":"Dan",
    "lastName": "Mensah",
    "email":"dd@gmail.com",
    "maritalStatus": "Married",
    "employmentStatus": "Retired",
    "employer": "Mangland",
    "dateOfBirth": "1/10/23",
    "cardType": "NHIS",
    "cardUniqueNo": "NHIS001324",
    "address": "Kokomlemle",
    "phoneNumber": "+23354243"
}

