### Register as a Customer
POST http://localhost:3000/api/customers/
Content-Type: application/json

{
    "firstName":"Jake",
    "lastName": "Kpodo",
    "email":"jakekpodo@gmail.com",
    "maritalStatus": "SINGLE",
    "employmentStatus": "STUDENT",
    "employer": "Meta",
    "dateOfBirth": "1994-04-06T00:00:00Z",
    "cardType": "NHIS",
    "cardUniqueNo": "NHIS02843",
    "address": "Accra, East Legon",
    "phoneNumber": "+233542433262"
}


### GET ALL CUSTOMER LOANS
GET http://localhost:3000/api/customers/
Content-Type: application/json



