### Register as a Customer
POST http://localhost:3000/api/customers/
Content-Type: application/json

{
    "firstName":"Doreen",
    "lastName": "Narh",
    "email":"deenarh@gmail.com",
    "maritalStatus": "MARRIED",
    "employmentStatus": "UNEMPLOYED",
    "employer": "Actor",
    "dateOfBirth": "1994-04-06T00:00:00Z",
    "cardType": "DVLA",
    "cardUniqueNo": "NHIS001324",
    "address": "Kokomlemle",
    "phoneNumber": "+233542433262"
}


### GET ALL CUSTOMER LOANS
GET http://localhost:3000/api/customers/
Content-Type: application/json



